# Comment ^o.o^


# This file contains a label. Hence, the `l_`.
include ../characters/l_party.init
Golem \#5: 1

# A label.
@ environment
# <name>...: <val> [keyword]...
Water Current: 15 force # Inline comment.


@ goblins
include ../monsters/goblin_shaman.init
Red Wolves: 2 advantage # Inline comment.


# Must be able to escape the following common symbols in names:
# * Escape symbol, itself (\\)
# * Comment (\#)
# * Label (\@)
# * Definition separator (\:)
